name: action-download-artifact

on:
  workflow_call:
    secrets:
      SECRET_GITHUB_TOKEN:
        description: ''
        required: true
    inputs:
      artifact-package:
        required: true
        type: string
        description: 'The name of the package.'
        default: ""

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: download artifact
        id: download-deb-artifact
        run: |
          echo "inputs.artifact-package: ${{ inputs.artifact-package }}"
          echo "ARTIFACT_PATH=${{ inputs.artifact-package }}" >> $GITHUB_OUTPUT

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-package }}
          path: ${{ inputs.artifact-package }}

      - name: extract tar gz archive
        run: |
           set -x
           echo $(pwd)
           echo $(ls -1)
           echo "${{ env.ARTIFACT_PATH }}"
           sudo chown $(whoami):$(whoami) "${{ env.ARTIFACT_PATH }}"
           sudo chmod +x "${{ env.ARTIFACT_PATH }}"
           echo $(ls -laF)
          #  sudo apt-get install -f ./${{ inputs.artifact-package }}
