name: action-download-artifact

on:
  workflow_call:
    secrets:
      SECRET_GITHUB_TOKEN:
        description: ''
        required: true
    inputs:
      artifact-package:
        required: true
        type: string
        description: 'The name of the package.'
        default: ""

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: download artifact
        id: download-deb-artifact
        run: |
          echo "ARTIFACT_PATH=${{ inputs.artifact-package }}" >> $GITHUB_ENV

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-package }}

      - name: install ${{ env.ARTIFACT_PATH }}
        run: |
           sudo apt-cache search libunwind
           sudo apt-get update
           sudo apt-get upgrade -y
           sudo apt-get install -y libunwind-dev libunwind8 
           sudo chown $(whoami):$(whoami) "${{ env.ARTIFACT_PATH }}"
           sudo chmod +x ${{ env.ARTIFACT_PATH }}
           sudo apt-get install -f ./${{ env.ARTIFACT_PATH }}
