name: action-download-artifact

on:
  workflow_call:
    secrets:
      SECRET_GITHUB_TOKEN:
        description: ''
        required: true
    inputs:
      artifact-package:
        required: true
        type: string
        description: 'The name of the package.'
        default: ""

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-package }}

      - name: extract tar gz archive
        run: |
           set -x
           echo $(ls -1 )
           sudo chown $(whoami):$(whoami) ${{ inputs.artifact-package }}
           sudo chmod +x ${{ inputs.artifact-package }}
           sudo apt-get install -f ./${{ inputs.artifact-package }}
