name: Call a reusable workflow and use its outputs

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]


jobs:
  job1:
    uses: ronaldoevangelista/colcon_package_action_test/.github/workflows/reusable-workflow-1.yaml@feat-resuable-workflows

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
