
name: runner-ci-ros-reusable

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  setup:
    name: setup action runner
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

  setup-package-name:
    name: setup package name
    needs: [setup]
    permissions:
      id-token: write
      contents: read
    uses: ronaldoevangelista/colcon_package_action_test/.github/workflows/action-extract-package-name.yaml@feat-resuable-workflows
    with:
      repository-name: ${{ github.repository }}
      head-ref:  ${{ github.head_ref }}
    secrets:
      SECRET_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  setup-ros-colcon:
    name: setup app token
    needs: [setup-package-name]
    permissions:
      id-token: write
      contents: read
    uses: ronaldoevangelista/colcon_package_action_test/.github/workflows/runner-ci-lint.ymll@feat-resuable-workflows
    with:
      repository-name: "${{ github.repository }}"
      package-name: "${{ needs.setup-package-name.outputs.package-name }}"
    secrets:
      SECRET_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
