name: colcon-runner-humble
on:
  push:
    branches: ['master']
  pull_request:

permissions:
  contents: read  
  pull-requests: write 
  
jobs:
  setup:
    strategy:
      matrix:
        include:
          - ros: humble
            ubuntu: jammy
      fail-fast: false

    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest

    name: Colcon build and test
    steps:
    - name: Build Package
      id: action-ros-ci
      uses: ronaldoevangelista/colcon_ci_action@master
      with:
        package-name: |
          "colcon_package_action_test"
        import-token: ${{ secrets.PAT_ACTION_USER_CIBOT }}
        target-ros2-distro: ${{ matrix.ros }}
        skip-tests: false
        colcon-extra-args: --executor sequential
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc"],
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=-fprofile-arcs -ftest-coverage --coverage",
                "-DCMAKE_BUILD_TYPE=Debug"
              ]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
    
    - name: Report Coverage
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.PAT_ACTION_USER_CIBOT }}
        lcov-file: ${{ steps.action-ros-ci.outputs.ros-workspace-directory-name }}/locv/report_coverage.info
        delete-old-comments: true
