name: Run action runner

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest

    steps:
    - name: Acquiring action-ros-ci
      id: action-ros-ci
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: |
          colcon_package_action_test
        target-ros2-distro: humble
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\"",
                "-DBUILD_DOCS=ON"
              ]
            }
          }
    - name: Build and run tests
      continue-on-error: true
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        COLCON=$(whereis colcon | grep ":" | awk '{ split($13,a,"/"); print $2 }')
        cd ..
        $COLCON build --paths ${{github.workspace}} --event-handlers console_direct+
        $COLCON test --paths ${{github.workspace}} --return-code-on-test-failure --event-handlers console_direct+
