name: Run tests

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{steps.load.outputs.strategy}}

    steps:
      - name: Setup Checkout Colcon Action
        uses: actions/checkout@v3.3.0
        with:
          repository: ronaldoevangelista/setup-colcon-action
          ref: feat-colcon-ci
      - id: load
        run: echo "strategy=$(echo $(cat strategy.json))" >> $GITHUB_OUTPUT

  colcon:
    needs: [setup]
    strategy: ${{fromJson(needs.setup.outputs.strategy)}}
    runs-on: ${{matrix.os}}

    steps:
      - name: list apt-key
        shell: bash
        run: |
          sudo apt-key list
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://mirror.tuna.tsinghua.edu.cn/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt update
      - uses: actions/checkout@v3.3.0
      - uses: ros-tooling/setup-ros@0.5.0
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ronaldoevangelista/setup-colcon-action@feat-colcon-ci
