name: colcon-runner-humble

on:
  push:
    branches: ['master']
  pull_request:

env:
  REPOSITORY_NAME: ${{ github.repository }}
  CMAKE_ARGS: -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage --coverage"

jobs:
  setup:
    strategy:
      matrix:
        include:
          - ros: humble
            ubuntu: jammy
      fail-fast: false

    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest

    name: Colcon build and test
    steps:
    - name: Build Package
      id: action-ros-ci
      uses: ronaldoevangelista/colcon_ci_action@master
      with:
        package-name: |
          "colcon_package_action_test"
        import-token: ${{ secrets.PAT_ACTION_USER_CIBOT }}
        target-ros2-distro: ${{ matrix.ros }}
        skip-tests: false
        colcon-extra-args: --event-handlers console_direct+ --executor sequential
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc"],
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=-fprofile-arcs -ftest-coverage --coverage"
              ]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
        working-directory: ${{ steps.action-ros-ci.outputs.ros-workspace-directory-name }}

    - name: Runnning Coverage
      working-directory: ${{ steps.action-ros-ci.outputs.ros-workspace-directory-name }}
      shell: bash
      run: |
        echo "Runnning Coverage"
        echo "COVERAGE_INFO=$(cat ros_ws/lcov/total_coverage.info)" >> $GITHUB_OUTPUT
        echo "COVERAGE=$(cat ros_ws/coveragepy/.coverage)" >> $GITHUB_OUTPUT



#  Reading tracefile /__w/colcon_package_action_test/colcon_package_action_test/ros_ws/lcov/total_coverage.info
