name: colcon-runner-humble

on:
  push:
    branches: ['master']
  pull_request:

env:
  REPOSITORY_NAME: ${{ github.repository }}
  CMAKE_ARGS: -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage --coverage"

jobs:
  setup:
    strategy:
      matrix:
        include:
          - ros: humble
            ubuntu: jammy
      fail-fast: false

    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest

    name: Colcon Build
    steps:
    - name: Build Package
      id: action-ros-ci
      uses: ronaldoevangelista/colcon_ci_action@master
      with:
        package-name: |
          "colcon_package_action_test"
        import-token: ${{ secrets.PAT_ACTION_USER_CIBOT }}
        target-ros2-distro: ${{ matrix.ros }}
        skip-tests: true
        colcon-extra-args: --event-handlers console_direct+ --executor sequential
