name: Run tests

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{steps.load.outputs.strategy}}

    steps:
      - name: Setup Checkout Colcon Action
        uses: actions/checkout@v3
        with:
          repository: ronaldoevangelista/setup-colcon-action
          ref: feat-colcon-ci
      - id: load
        run: echo "strategy=$(echo $(cat strategy.json))" >> $GITHUB_OUTPUT

  colcon:
    needs: [setup]
    strategy: ${{fromJson(needs.setup.outputs.strategy)}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@0.5.0
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ronaldoevangelista/setup-colcon-action@feat-colcon-ci
