name: Steps from B

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v2
        with:
          name: colmap-artifact

      - name: Execute B
        run: |
          cat colmap-artifact.txt  # Lê o conteúdo do arquivo A
          echo "B executado com sucesso!"
