name: Steps from B

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: colmap-artifact

      - name: extract tar gz archive
        run: |
           set -x
           colmap.tar.gz
           tar -tvf colmap.tar.gz
