name: main

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3
     -
      run: |
        echo $(ls -1)
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=$(jq -c . < ./config.json)" >> $GITHUB_OUTPUT

  convert-lint-list:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
     - run: |
        for linter_item in ${{ toJson(matrix.linter) }}; do
          echo "Linter: $linter_item"
        done
        echo ${{ matrix.distro }}
        echo ${{ matrix.ubuntu }}
        echo ${{ matrix.package }}

  ament_lint_general:
    name: ament_${{ matrix.linter }}
    needs: configure
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}

    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest
    steps:
    -
      if: ${{ matrix.linter == 'cpplint' || matrix.linter == 'uncrustify' }}
      name: Set env ${{ matrix.linter }}
      run: |
          echo "LINT_ARGUMENTS=--linelength=120" >> $GITHUB_ENV
