name: main

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  configure:
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [jammy]
        distro: [humble]
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: install dependencies
       run: |
         sudo apt-get update -y | true
         sudo apt-get install -y \
              git \
              cmake \
              ninja-build \
              build-essential \
              libboost-program-options-dev \
              libboost-filesystem-dev \
              libboost-graph-dev \
              libboost-system-dev \
              libeigen3-dev \
              libflann-dev \
              libfreeimage-dev \
              libmetis-dev \
              libgoogle-glog-dev \
              libgtest-dev \
              libsqlite3-dev \
              libglew-dev \
              qtbase5-dev \
              libqt5opengl5-dev \
              libcgal-dev \
              libceres-dev

     - name: update indices
       run: |
         sudo apt-get update -y | true
         sudo apt-get upgrade -y | true

     - name: compile colmap
       shell: bash
       run: |
         mkdir -p /__w/colmap_ws/
         cd /__w/colmap_ws/
         git clone https://github.com/colmap/colmap.git
         cd colmap
         mkdir build
         cd build
         cmake .. -GNinja
         ninja
         sudo ninja install
         colmap -h
