name: main-action

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  setup:
    name: setup action runner
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

  setup-dependencies:
    name: setup dependencies
    needs: [setup]
    permissions:
      id-token: write
      contents: read
    uses: ronaldoevangelista/colcon_package_action_test/.github/workflows/action-extract-dependencies.yaml@feat-colmap
    with:
      repository-name: ${{ github.repository }}
      head-ref:  ${{ github.head_ref }}
    secrets:
      SECRET_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  setup-publish-artifact:
    name: setup publish artifact
    needs: [setup, setup-dependencies]
    permissions:
      id-token: write
      contents: read
    uses: ronaldoevangelista/colcon_package_action_test/.github/workflows/action-third-party-artifact.yaml@feat-colmap
    with:
      repository-package: "${{ needs.setup-dependencies.outputs.repository-thirdparty-list }}"
      repository-version: "3.7"
      dependencies-list: |
              libboost-program-options-dev
              libboost-filesystem-dev
              libboost-graph-dev
              libboost-system-dev
              libeigen3-dev
              libflann-dev
              libfreeimage-dev
              libmetis-dev
              libunwind-dev
              libunwind8
              libgoogle-glog-dev
              libgtest-dev
              libsqlite3-dev
              libglew-dev
              qtbase5-dev
              libqt5opengl5-dev
              libcgal-dev
              libceres-dev
              libcgal-dev
              libfftw3-dev
              libclfft-dev
      string-build: |
              mkdir -p build install &&
              cd build &&
              cmake ../colmap \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=../install \
              -DCMAKE_CUDA_ARCHITECTURES=50 \
              -DTESTS_ENABLED=OFF \
              -DCUDA_ENABLED=false \
              -DGUI_ENABLED=false \
              -DASAN_ENABLED=false \
              -DCGAL_DATA_DIR=. &&
              ninja -k 10000 &&
              ninja install
    secrets:
      SECRET_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  setup-download-artifact:
    name: setup download artifact
    needs: [setup-publish-artifact]
    permissions:
      id-token: write
      contents: read
    uses: ronaldoevangelista/colcon_package_action_test/.github/workflows/action-download-artifact.yaml@feat-colmap
    with:
      artifact-package: "${{ needs.setup-publish-artifact.outputs.artifact-path }}"
    secrets:
      SECRET_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
