name: main-action

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  setup:
    name: setup action runner
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: execute publish artifact
        shell: bash
        run: |
          echo $(pwd)
          echo $(ls -1 )

  setup-publish-artifact:
    name: setup publish artifact
    needs: [setup]
    permissions:
      id-token: write
      contents: read
    uses: ronaldoevangelista/colcon_package_action_test/.github/workflows/publish-artifact.yaml@feat-colmap
    with:
      repository-name: ${{ github.repository }}
    secrets:
      SECRET_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"


  setup-download-artifact:
    name: setup download artifact
    needs: [setup-publish-artifact]
    permissions:
      id-token: write
      contents: read
    uses: ronaldoevangelista/colcon_package_action_test/.github/workflows/download-artifact.yaml@feat-colmap
