name: execute-publish-artifact

on:
  workflow_call:
    secrets:
      SECRET_GITHUB_TOKEN:
        description: ''
        required: true
    inputs:
      repository-name:
        required: true
        type: string
        description: 'The name of the repository from which to extract dependencies.'
        default: ${{ github.repository }}

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute publish
        run: |
          echo "Conteúdo do arquivo A" > colmap-artifact.txt
          echo "A executado com sucesso!"

      - name: Publicar artefato
        uses: actions/upload-artifact@v2
        with:
          name: colmap-artifact
          path: colmap-artifact.txt
          retention-days: 1
