name: Steps from A

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Execute A
        run: |
          echo "Conteúdo do arquivo A" > a.txt
          echo "A executado com sucesso!"

      - name: Publicar artefato
        uses: actions/upload-artifact@v2
        with:
          name: colmap-artifact
          path: colmap-artifact.txt
          retention-days: 1
